name: Build Snowflake Extension
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout DuckDB
        run: |
          cd duckdb
          git checkout v1.3.1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build libssl-dev

      - name: Build
        run: |
          make release-snowflake 