name: Build Snowflake Extension
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        duckdb_version: ['v1.3.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Build Tools (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build

      - name: Install Build Tools (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install ninja

      - name: Install Build Tools (Windows)
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Checkout DuckDB
        run: |
          cd duckdb
          git checkout ${{ matrix.duckdb_version }}

      - name: Setup vcpkg manually
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          git checkout master
          ./bootstrap-vcpkg.sh
          cd ..
          echo "VCPKG setup complete"
          ls -la vcpkg/scripts/buildsystems/

      - name: Build
        env:
          VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          VCPKG_TARGET_TRIPLET: ${{ matrix.os == 'ubuntu-latest' && 'x64-linux' || matrix.os == 'macos-latest' && 'x64-osx' || 'x64-windows-static-md' }}
          VCPKG_MANIFEST_DIR: ${{ github.workspace }}
          GEN: ${{ matrix.os == 'windows-latest' && '' || 'ninja' }}
          VCPKG_FEATURE_FLAGS: manifests
        run: make release-snowflake 