#
# NOTE: this workflow is for testing the extension template itself,
#     this workflow will be removed when scripts/bootstrap-template.py is run
#
name: Extension Template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Enable GitHub Actions to create pull requests
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # Fast build check - only build the extension, not full DuckDB
  quick-build-check:
    name: Quick Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.28'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '53bef8994c541b6561884a8395ea35715ece75db'

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_ROOT }}/installed
          key: vcpkg-ubuntu-snowflake
          restore-keys: |
            vcpkg-ubuntu-

      - name: Rename extension
        run: |
          python scripts/bootstrap-template.py snowflake

      - name: Build Extension Only
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DEXTENSION_STATIC_BUILD=1 -DDUCKDB_EXTENSION_CONFIGS=$GITHUB_WORKSPACE/extension_config.cmake -S ../duckdb/
          cmake --build . --target snowflake_extension --parallel

  # Full build and test
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [quick-build-check]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.28'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '53bef8994c541b6561884a8395ea35715ece75db'

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_ROOT }}/installed
          key: vcpkg-ubuntu-snowflake
          restore-keys: |
            vcpkg-ubuntu-

      - name: Rename extension
        run: |
          python scripts/bootstrap-template.py snowflake

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DEXTENSION_STATIC_BUILD=1 -DDUCKDB_EXTENSION_CONFIGS=$GITHUB_WORKSPACE/extension_config.cmake -S ../duckdb/
          cmake --build . --parallel

      - name: Test
        run: |
          cd build
          # Run only extension-specific tests
          ./test/unittest "test/sql/snowflake*"

  # Windows build
  windows-build:
    name: Windows Build
    runs-on: windows-latest
    needs: [quick-build-check]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.28'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '53bef8994c541b6561884a8395ea35715ece75db'

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_ROOT }}/installed
          key: vcpkg-windows-snowflake
          restore-keys: |
            vcpkg-windows-

      - name: Rename extension
        run: |
          python scripts/bootstrap-template.py snowflake

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DEXTENSION_STATIC_BUILD=1 -DDUCKDB_EXTENSION_CONFIGS=$GITHUB_WORKSPACE/extension_config.cmake -S ../duckdb/
          cmake --build . --config Release --parallel

      - name: Test extension
        run: |
          cd build
          # Run only extension-specific tests
          ./test/Release/unittest.exe "test/sql/snowflake*"

  # macOS build
  macos-build:
    name: macOS Build
    runs-on: macos-latest
    needs: [quick-build-check]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.28'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '53bef8994c541b6561884a8395ea35715ece75db'

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_ROOT }}/installed
          key: vcpkg-macos-snowflake
          restore-keys: |
            vcpkg-macos-

      - name: Rename extension
        run: |
          python scripts/bootstrap-template.py snowflake

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DEXTENSION_STATIC_BUILD=1 -DDUCKDB_EXTENSION_CONFIGS=$GITHUB_WORKSPACE/extension_config.cmake -S ../duckdb/
          cmake --build . --parallel

      - name: Test extension
        run: |
          cd build
          # Run only extension-specific tests
          ./test/unittest "test/sql/snowflake*"
