name: Fast Build Test
on:
  workflow_dispatch:
  push:
    branches: [ "working-from-summer2025" ]

jobs:
  quick-build-test:
    name: Quick Build Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Free Disk Space (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h

      - name: Free Disk Space (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          sudo rm -rf /Applications/Xcode_*.app
          brew cleanup --prune=all
          df -h

      - name: Install build tools (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build

      - name: Install build tools (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake ninja

      - name: Install build tools (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake ninja

      - name: Build extension
        run: |
          make release

      - name: Test extension loading
        run: |
          cd build/release
          ./duckdb -c "LOAD './build/release/extension/snowflake/snowflake.duckdb_extension'; SELECT 'Extension loaded successfully' as result;"

      - name: Show build artifacts
        run: |
          find build/release -name "*.duckdb_extension" -ls || echo "No extension files found" 