#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries (stable)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.3.1
    with:
      duckdb_version: v1.1.3  # Use older stable version to avoid API issues
      ci_tools_version: v1.3.1
      extension_name: snowflake
      # Exclude all problematic architectures to ensure builds work
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;linux_arm64;linux_arm64_gcc4;osx_arm64;windows_amd64_mingw'

  code-quality-check:
    name: Code Quality Check  
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@main
    with:
      duckdb_version: v1.1.3  # Use same stable version
      ci_tools_version: main
      extension_name: snowflake
      format_checks: 'format;tidy'
